In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
36   34  Female     Good        UG       Yes
38   45  Female     Good    School        No
28   48    Male     Poor    School        No
21   32    Male  Average        PG        No
30   73    Male  Average        UG        No

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [17]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [22]:
X_train = oe.transform(X_train)



c:\Users\dandu\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(
c:\Users\dandu\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:579: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
c:\Users\dandu\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [19]:
X_train

array([[2., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 0.]])

In [23]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [87]:
X_train

array([[1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.]])

In [95]:
from sklearn.preprocessing import LabelEncoder

In [96]:
le = LabelEncoder()

In [97]:
le.fit(y_train)

LabelEncoder()

In [98]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [99]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [100]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])